sudo: required
services:
  - docker
language: python
before_install:
- docker run -d -p 8001:8000 dwmkerr/dynamodb
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install .
script: py.test
